name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Build
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --configuration Release

      # The 11 below is the number of characters of
      # `refs/tags/v` which is what the version is prefixed with
      # in `${GITHUB_REF}`.
      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF:11}

      - name: Generate nuget package
        run: dotnet pack --configuration Release /p:PackageVersion=${{ steps.version.outputs.VERSION }} -o pkg

      - name: Publish nuget package
        run: nuget push pkg/HotChocolate.Types.NodaTime.${{ steps.version.outputs.VERSION }}.nupkg -k $nuget_api_key -s "https://api.nuget.org/v3/index.json" --skip-duplicate
        env:
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}